/// ------------------------------------------------------------------------------
/// <auto-generated>
/// Auto-generated file, don't modify it manually.
/// </auto-generated>
/// ------------------------------------------------------------------------------

using System.Collections.Generic;

namespace GamePlay.Table
{
    [System.Serializable]
    public class UiLayerItem
    {
        public int Id;
        public string Name;
        public int SortingOrder;
        public int StackSwitchType;
    }

    [System.Serializable]
    public class UiLayer
    {
        public Dictionary<int, UiLayerItem> Items;

        public UiLayerItem GetItemById(int id)
        {
            return Items.TryGetValue(id, out var item) ? item : null;
        }
    }
}
