/// ------------------------------------------------------------------------------
/// <auto-generated>
/// Auto-generated file, don't modify it manually.
/// </auto-generated>
/// ------------------------------------------------------------------------------

using System.Collections.Generic;

namespace GamePlay.Table
{
    [System.Serializable]
    public class UiPanelItem
    {
        public int Id;
        public string Name;
        public string Address;
        public int ParentLayer;
    }

    [System.Serializable]
    public class UiPanel
    {
        public Dictionary<int, UiPanelItem> Items;

        public UiPanelItem GetItemById(int id)
         {
             return Items.TryGetValue(id, out var item) ? item : null;
         }
    }
}
