/// ------------------------------------------------------------------------------
/// <auto-generated>
/// Generated by ConfigClassGenerator, don't modify it manually.
/// </auto-generated>
/// ------------------------------------------------------------------------------

using System.Collections.Generic;

namespace GameConfig
{
    [System.Serializable]
    public class UiLayer
    {
        public int Id;
        public string Name;
        public int SortingOrder;
        public int StackSwitchType;
    }

    [System.Serializable]
    public class UiLayerTable
    {
        public Dictionary<int, UiLayer> AllConfigs;

        public UiLayer GetConfigById(int id)
         {
             return AllConfigs.TryGetValue(id, out var config) ? config : null;
         }
    }
}
