/// ------------------------------------------------------------------------------
/// <auto-generated>
/// Generated by ConfigClassGenerator, don't modify it manually.
/// </auto-generated>
/// ------------------------------------------------------------------------------

using System.Collections.Generic;

namespace GameConfig
{
    [System.Serializable]
    public class UiPanel
    {
        public int Id;
        public string Name;
        public string Address;
        public int ParentLayer;
    }

    [System.Serializable]
    public class UiPanelTable
    {
        public Dictionary<int, UiPanel> AllConfigs;

        public UiPanel GetConfigById(int id)
         {
             return AllConfigs.TryGetValue(id, out var config) ? config : null;
         }
    }
}
