/// ------------------------------------------------------------------------------
/// <auto-generated>
/// Auto-generated file, don't modify it manually.
/// </auto-generated>
/// ------------------------------------------------------------------------------

using System.Collections.Generic;
using XGame.Core;

namespace XGame.Table
{
    [System.Serializable]
    public class ConfigUiLayers : IConfig
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int SortingOrder { get; set; }
        public int StackSwitchType { get; set; }
    }

    [System.Serializable]
    public class TableUiLayers
    {
        public Dictionary<int, ConfigUiLayers> Configs;

        public ConfigUiLayers GetConfigById(int id)
         {
             return Configs.TryGetValue(id, out var config) ? config : null;
         }
    }
}
