/// ------------------------------------------------------------------------------
/// <auto-generated>
/// Auto-generated file, don't modify it manually.
/// </auto-generated>
/// ------------------------------------------------------------------------------

using Newtonsoft.Json;
using System.Collections.Generic;

namespace XGame.Data
{
    [System.Serializable]
    public class ConfigUiPanels : IConfig
    {
        [JsonProperty("id")]
        public int Id { get; set; }
        
        [JsonProperty("name")]
        public string Name { get; set; }
        
        [JsonProperty("address")]
        public string Address { get; set; }
        
        [JsonProperty("parent_layer")]
        public int ParentLayer { get; set; }
        
    }

    [System.Serializable]
    public class TableUiPanels
    {
        public Dictionary<int, ConfigUiPanels> Configs;

        public ConfigUiPanels GetConfigById(int id)
         {
             return Configs.TryGetValue(id, out var config) ? config : null;
         }
    }
}
