/// ------------------------------------------------------------------------------
/// <auto-generated>
/// Auto-generated file, don't modify it manually.
/// </auto-generated>
/// ------------------------------------------------------------------------------

using System.Collections.Generic;
using XGame.Core;

namespace XGame.Table
{
    [System.Serializable]
    public class ConfigUiPanels : IConfig
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int ParentLayer { get; set; }
    }

    [System.Serializable]
    public class TableUiPanels
    {
        public Dictionary<int, ConfigUiPanels> Configs;

        public ConfigUiPanels GetConfigById(int id)
         {
             return Configs.TryGetValue(id, out var config) ? config : null;
         }
    }
}
