/// ------------------------------------------------------------------------------
/// <auto-generated>
/// Auto-generated file, don't modify it manually.
/// </auto-generated>
/// ------------------------------------------------------------------------------

using System.Collections.Generic;
using XGame.Core;

namespace XGame.Table
{
    [System.Serializable]
    public class UiLayerItem : ITableItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int SortingOrder { get; set; }
        public int StackSwitchType { get; set; }
    }

    [System.Serializable]
    public class UiLayer
    {
        public Dictionary<int, UiLayerItem> Items;

        public UiLayerItem GetItemById(int id)
        {
            return Items.TryGetValue(id, out var item) ? item : null;
        }
    }
}
