/// ------------------------------------------------------------------------------
/// <auto-generated>
/// Auto-generated file, don't modify it manually.
/// </auto-generated>
/// ------------------------------------------------------------------------------

using System.Collections.Generic;
using XGame.Core;

namespace XGame.Table
{
    [System.Serializable]
    public class UiPanelItem : ITableItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int ParentLayer { get; set; }
    }

    [System.Serializable]
    public class UiPanel
    {
        public Dictionary<int, UiPanelItem> Items;

        public UiPanelItem GetItemById(int id)
        {
            return Items.TryGetValue(id, out var item) ? item : null;
        }
    }
}
