/// ------------------------------------------------------------------------------
/// <auto-generated>
/// Auto-generated file, don't modify it manually.
/// </auto-generated>
/// ------------------------------------------------------------------------------

using Newtonsoft.Json;
using System.Collections.Generic;

namespace XGame.Data
{
    [System.Serializable]
    public class ConfigUiLayers : IConfig
    {
        [JsonProperty("id")]
        public int Id { get; set; }
        
        [JsonProperty("name")]
        public string Name { get; set; }
        
        [JsonProperty("sorting_order")]
        public int SortingOrder { get; set; }
        
        [JsonProperty("stack_switch_type")]
        public int StackSwitchType { get; set; }
        
    }

    [System.Serializable]
    public class TableUiLayers
    {
        public Dictionary<int, ConfigUiLayers> Configs;

        public ConfigUiLayers GetConfigById(int id)
         {
             return Configs.TryGetValue(id, out var config) ? config : null;
         }
    }
}
