/// ------------------------------------------------------------------------------
/// <auto-generated>
/// Generated by ConfigClassGenerator, don't modify it manually.
/// </auto-generated>
/// ------------------------------------------------------------------------------

using System.Collections.Generic;
using XFramework;

namespace GameConfig
{
    [System.Serializable]
    public class UiLayer : IConfig
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int SortingOrder { get; set; }
        public int StackSwitchType { get; set; }
    }

    [System.Serializable]
    public class UiLayerTable
    {
        public Dictionary<int, UiLayer> AllConfigs;

        public UiLayer GetConfigById(int id)
        {
            return AllConfigs.TryGetValue(id, out var config) ? config : null;
        }
    }
}
