/// ------------------------------------------------------------------------------
/// <auto-generated>
/// Generated by ConfigClassGenerator, don't modify it manually.
/// </auto-generated>
/// ------------------------------------------------------------------------------

using System.Collections.Generic;
using XFramework;

namespace GameConfig
{
    [System.Serializable]
    public class UiPanel : IConfig
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int ParentLayer { get; set; }
    }

    [System.Serializable]
    public class UiPanelTable
    {
        public Dictionary<int, UiPanel> AllConfigs;

        public UiPanel GetConfigById(int id)
        {
            return AllConfigs.TryGetValue(id, out var config) ? config : null;
        }
    }
}
