/// ------------------------------------------------------------------------------
/// <auto-generated>
/// Generated by ConfigClassGenerator, don't modify it manually.
/// </auto-generated>
/// ------------------------------------------------------------------------------

using System.Collections.Generic;

namespace GameConfig
{
    [System.Serializable]
    public class UiLayerConfig : XFramework.IConfig
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int SortingOrder { get; set; }
        public int StackSwitchType { get; set; }
    }

    [System.Serializable]
    public class UiLayerConfigTable
    {
        public Dictionary<int, UiLayerConfig> AllConfigs;

        public UiLayerConfig GetConfigById(int id)
         {
             return AllConfigs.TryGetValue(id, out var config) ? config : null;
         }
    }
}
