/// ------------------------------------------------------------------------------
/// <auto-generated>
/// Generated by ConfigClassGenerator, don't modify it manually.
/// </auto-generated>
/// ------------------------------------------------------------------------------

using System.Collections.Generic;

namespace GameConfig
{
    [System.Serializable]
    public class UiPanelConfig : XFramework.IConfig
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int ParentLayer { get; set; }
    }

    [System.Serializable]
    public class UiPanelConfigTable
    {
        public Dictionary<int, UiPanelConfig> AllConfigs;

        public UiPanelConfig GetConfigById(int id)
         {
             return AllConfigs.TryGetValue(id, out var config) ? config : null;
         }
    }
}
